In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import Image
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [12]:
df =pd.read_csv('test.csv')
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.00,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.00,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.00,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.2292,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.00,2,0,A/4 48871,24.1500,NaN,S
10,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
11,903,1,"Jones, Mr. Charles Cresson",male,46.00,0,0,694,26.0000,NaN,S
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00,1,0,21228,82.2667,B45,S
13,905,2,"Howard, Mr. Benjamin",male,63.00,1,0,24065,26.0000,NaN,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.00,1,0,W.E.P. 5734,61.1750,E31,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.00,1,0,SC/PARIS 2167,27.7208,NaN,C
16,908,2,"Keane, Mr. Daniel",male,35.00,0,0,233734,12.3500,NaN,Q
17,909,3,"Assaf, Mr. Gerios",male,21.00,0,0,2692,7.2250,NaN,C
18,910,3,"Ilmakangas, Miss. Ida Livija",female,27.00,1,0,STON/O2. 3101270,7.9250,NaN,S
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.00,0,0,2696,7.2250,NaN,C
20,912,1,"Rothschild, Mr. Martin",male,55.00,1,0,PC 17603,59.4000,NaN,C
21,913,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,NaN,S
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S
23,915,1,"Williams, Mr. Richard Norris II",male,21.00,0,1,PC 17597,61.3792,NaN,C
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
25,917,3,"Robins, Mr. Alexander A",male,50.00,1,0,A/5. 3337,14.5000,NaN,S
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.00,0,1,113509,61.9792,B36,C
27,919,3,"Daher, Mr. Shedid",male,22.50,0,0,2698,7.2250,NaN,C
28,920,1,"Brady, Mr. John Bertram",male,41.00,0,0,113054,30.5000,A21,S
29,921,3,"Samaan, Mr. Elias",male,NaN,2,0,2662,21.6792,NaN,C
30,922,2,"Louch, Mr. Charles Alexander",male,50.00,1,0,SC/AH 3085,26.0000,NaN,S
31,923,2,"Jefferys, Mr. Clifford Thomas",male,24.00,2,0,C.A. 31029,31.5000,NaN,S
32,924,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.00,1,2,C.A. 2315,20.5750,NaN,S
33,925,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
34,926,1,"Mock, Mr. Philipp Edmund",male,30.00,1,0,13236,57.7500,C78,C
35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.50,0,0,2682,7.2292,NaN,C
36,928,3,"Roth, Miss. Sarah A",female,NaN,0,0,342712,8.0500,NaN,S
37,929,3,"Cacic, Miss. Manda",female,21.00,0,0,315087,8.6625,NaN,S
38,930,3,"Sap, Mr. Julius",male,25.00,0,0,345768,9.5000,NaN,S
39,931,3,"Hee, Mr. Ling",male,NaN,0,0,1601,56.4958,NaN,S
40,932,3,"Karun, Mr. Franz",male,39.00,0,1,349256,13.4167,NaN,C
41,933,1,"Franklin, Mr. Thomas Parham",male,NaN,0,0,113778,26.5500,D34,S
42,934,3,"Goldsmith, Mr. Nathan",male,41.00,0,0,SOTON/O.Q. 3101263,7.8500,NaN,S
43,935,2,"Corbett, Mrs. Walter H (Irene Colvin)",female,30.00,0,0,237249,13.0000,NaN,S
44,936,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.00,1,0,11753,52.5542,D19,S
45,937,3,"Peltomaki, Mr. Nikolai Johannes",male,25.00,0,0,STON/O 2. 3101291,7.9250,NaN,S
46,938,1,"Chevre, Mr. Paul Romaine",male,45.00,0,0,PC 17594,29.7000,A9,C
47,939,3,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q
48,940,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00,0,0,11813,76.2917,D15,C
49,941,3,"Coutts, Mrs. William (Winnie Minnie"" Treanor)""",female,36.00,0,2,C.A. 37671,15.9000,NaN,S
50,942,1,"Smith, Mr. Lucien Philip",male,24.00,1,0,13695,60.0000,C31,S
51,943,2,"Pulbaum, Mr. Franz",male,27.00,0,0,SC/PARIS 2168,15.0333,NaN,C
52,944,2,"Hocking, Miss. Ellen Nellie""""",female,20.00,2,1,29105,23.0000,NaN,S
53,945,1,"Fortune, Miss. Ethel Flora",female,28.00,3,2,19950,263.0000,C23 C25 C27,S
54,946,2,"Mangiavacchi, Mr. Serafino Emilio",male,NaN,0,0,SC/A.3 2861,15.5792,NaN,C
55,947,3,"Rice, Master. Albert",male,10.00,4,1,382652,29.1250,NaN,Q
56,948,3,"Cor, Mr. Bartol",male,35.00,0,0,349230,7.8958,NaN,S
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.00,0,0,348122,7.6500,F G63,S
58,950,3,"Davison, Mr. Thomas Henry",male,NaN,1,0,386525,16.1000,NaN,S
59,951,1,"Chaudanson, Miss. Victorine",female,36.00,0,0,PC 17608,262.3750,B61,C
60,952,3,"Dika, Mr. Mirko",male,17.00,0,0,349232,7.8958,NaN,S
61,953,2,"McCrae, Mr. Arthur Gordon",male,32.00,0,0,237216,13.5000,NaN,S
62,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.00,0,0,347090,7.7500,NaN,S
63,955,3,"Bradley, Miss. Bridget Delia",female,22.00,0,0,334914,7.7250,NaN,Q
64,956,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
65,957,2,"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Mi...",female,NaN,0,0,F.C.C. 13534,21.0000,NaN,S
66,958,3,"Burns, Miss. Mary Delia",female,18.00,0,0,330963,7.8792,NaN,Q
67,959,1,"Moore, Mr. Clarence Bloomfield",male,47.00,0,0,113796,42.4000,NaN,S
68,960,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.00,0,0,2543,28.5375,C53,C
69,961,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00,1,4,19950,263.0000,C23 C25 C27,S
70,962,3,"Mulvihill, Miss. Bertha E",female,24.00,0,0,382653,7.7500,NaN,Q
71,963,3,"Minkoff, Mr. Lazar",male,21.00,0,0,349211,7.8958,NaN,S
72,964,3,"Nieminen, Miss. Manta Josefina",female,29.00,0,0,3101297,7.9250,NaN,S
73,965,1,"Ovies y Rodriguez, Mr. Servando",male,28.50,0,0,PC 17562,27.7208,D43,C
74,966,1,"Geiger, Miss. Amalie",female,35.00,0,0,113503,211.5000,C130,C
75,967,1,"Keeping, Mr. Edwin",male,32.50,0,0,113503,211.5000,C132,C
76,968,3,"Miles, Mr. Frank",male,NaN,0,0,359306,8.0500,NaN,S
77,969,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.00,2,0,11770,25.7000,C101,S
78,970,2,"Aldworth, Mr. Charles Augustus",male,30.00,0,0,248744,13.0000,NaN,S
79,971,3,"Doyle, Miss. Elizabeth",female,24.00,0,0,368702,7.7500,NaN,Q
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C
81,973,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.7792,C55 C57,S
82,974,1,"Case, Mr. Howard Brown",male,49.00,0,0,19924,26.0000,NaN,S
83,975,3,"Demetri, Mr. Marinko",male,NaN,0,0,349238,7.8958,NaN,S
84,976,2,"Lamb, Mr. John Joseph",male,NaN,0,0,240261,10.7083,NaN,Q
85,977,3,"Khalil, Mr. Betros",male,NaN,1,0,2660,14.4542,NaN,C
86,978,3,"Barry, Miss. Julia",female,27.00,0,0,330844,7.8792,NaN,Q
87,979,3,"Badman, Miss. Emily Louisa",female,18.00,0,0,A/4 31416,8.0500,NaN,S
88,980,3,"O'Donoghue, Ms. Bridget",female,NaN,0,0,364856,7.7500,NaN,Q
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S
90,982,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.00,1,0,347072,13.9000,NaN,S
91,983,3,"Pedersen, Mr. Olaf",male,NaN,0,0,345498,7.7750,NaN,S
92,984,1,"Davidson, Mrs. Thornton (Orian Hays)",female,27.00,1,2,F.C. 12750,52.0000,B71,S
93,985,3,"Guest, Mr. Robert",male,NaN,0,0,376563,8.0500,NaN,S
94,986,1,"Birnbaum, Mr. Jakob",male,25.00,0,0,13905,26.0000,NaN,C
95,987,3,"Tenglin, Mr. Gunnar Isidor",male,25.00,0,0,350033,7.7958,NaN,S
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.8500,C46,S
97,989,3,"Makinen, Mr. Kalle Edvard",male,29.00,0,0,STON/O 2. 3101268,7.9250,NaN,S
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.00,0,0,347471,7.8542,NaN,S
99,991,3,"Nancarrow, Mr. William Henry",male,33.00,0,0,A./5. 3338,8.0500,NaN,S
100,992,1,"Stengel, Mrs. Charles Emil Henry (Annie May Mo...",female,43.00,1,0,11778,55.4417,C116,C
101,993,2,"Weisz, Mr. Leopold",male,27.00,1,0,228414,26.0000,NaN,S
102,994,3,"Foley, Mr. William",male,NaN,0,0,365235,7.7500,NaN,Q
103,995,3,"Johansson Palmquist, Mr. Oskar Leander",male,26.00,0,0,347070,7.7750,NaN,S
104,996,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.00,1,1,2625,8.5167,NaN,C
105,997,3,"Holthen, Mr. Johan Martin",male,28.00,0,0,C 4001,22.5250,NaN,S
106,998,3,"Buckley, Mr. Daniel",male,21.00,0,0,330920,7.8208,NaN,Q
107,999,3,"Ryan, Mr. Edward",male,NaN,0,0,383162,7.7500,NaN,Q
108,1000,3,"Willer, Mr. Aaron (Abi Weller"")""",male,NaN,0,0,3410,8.7125,NaN,S
109,1001,2,"Swane, Mr. George",male,18.50,0,0,248734,13.0000,F,S
110,1002,2,"Stanton, Mr. Samuel Ward",male,41.00,0,0,237734,15.0458,NaN,C
111,1003,3,"Shine, Miss. Ellen Natalia",female,NaN,0,0,330968,7.7792,NaN,Q
112,1004,1,"Evans, Miss. Edith Corse",female,36.00,0,0,PC 17531,31.6792,A29,C
113,1005,3,"Buckley, Miss. Katherine",female,18.50,0,0,329944,7.2833,NaN,Q
114,1006,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00,1,0,PC 17483,221.7792,C55 C57,S
115,1007,3,"Chronopoulos, Mr. Demetrios",male,18.00,1,0,2680,14.4542,NaN,C
116,1008,3,"Thomas, Mr. John",male,NaN,0,0,2681,6.4375,NaN,C
117,1009,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S
118,1010,1,"Beattie, Mr. Thomson",male,36.00,0,0,13050,75.2417,C6,C
119,1011,2,"Chapman, Mrs. John Henry (Sara Elizabeth Lawry)",female,29.00,1,0,SC/AH 29037,26.0000,NaN,S
120,1012,2,"Watt, Miss. Bertha J",female,12.00,0,0,C.A. 33595,15.7500,NaN,S
121,1013,3,"Kiernan, Mr. John",male,NaN,1,0,367227,7.7500,NaN,Q
122,1014,1,"Schabert, Mrs. Paul (Emma Mock)",female,35.00,1,0,13236,57.7500,C28,C
123,1015,3,"Carver, Mr. Alfred John",male,28.00,0,0,392095,7.2500,NaN,S
124,1016,3,"Kennedy, Mr. John",male,NaN,0,0,368783,7.7500,NaN,Q
125,1017,3,"Cribb, Miss. Laura Alice",female,17.00,0,1,371362,16.1000,NaN,S
126,1018,3,"Brobeck, Mr. Karl Rudolf",male,22.00,0,0,350045,7.7958,NaN,S
127,1019,3,"McCoy, Miss. Alicia",female,NaN,2,0,367226,23.2500,NaN,Q
128,1020,2,"Bowenur, Mr. Solomon",male,42.00,0,0,211535,13.0000,NaN,S
129,1021,3,"Petersen, Mr. Marius",male,24.00,0,0,342441,8.0500,NaN,S
130,1022,3,"Spinner, Mr. Henry John",male,32.00,0,0,STON/OQ. 369943,8.0500,NaN,S
131,1023,1,"Gracie, Col. Archibald IV",male,53.00,0,0,113780,28.5000,C51,C
132,1024,3,"Lefebre, Mrs. Frank (Frances)",female,NaN,0,4,4133,25.4667,NaN,S
133,1025,3,"Thomas, Mr. Charles P",male,NaN,1,0,2621,6.4375,NaN,C
134,1026,3,"Dintcheff, Mr. Valtcho",male,43.00,0,0,349226,7.8958,NaN,S
135,1027,3,"Carlsson, Mr. Carl Robert",male,24.00,0,0,350409,7.8542,NaN,S
136,1028,3,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C
137,1029,2,"Schmidt, Mr. August",male,26.00,0,0,248659,13.0000,NaN,S
138,1030,3,"Drapkin, Miss. Jennie",female,23.00,0,0,SOTON/OQ 392083,8.0500,NaN,S
139,1031,3,"Goodwin, Mr. Charles Frederick",male,40.00,1,6,CA 2144,46.9000,NaN,S
140,1032,3,"Goodwin, Miss. Jessie Allis",female,10.00,5,2,CA 2144,46.9000,NaN,S
141,1033,1,"Daniels, Miss. Sarah",female,33.00,0,0,113781,151.5500,NaN,S
142,1034,1,"Ryerson, Mr. Arthur Larned",male,61.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
143,1035,2,"Beauchamp, Mr. Henry James",male,28.00,0,0,244358,26.0000,NaN,S
144,1036,1,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lin...",male,42.00,0,0,17475,26.5500,NaN,S
145,1037,3,"Vander Planke, Mr. Julius",male,31.00,3,0,345763,18.0000,NaN,S
146,1038,1,"Hilliard, Mr. Herbert Henry",male,NaN,0,0,17463,51.8625,E46,S
147,1039,3,"Davies, Mr. Evan",male,22.00,0,0,SC/A4 23568,8.0500,NaN,S
148,1040,1,"Crafton, Mr. John Bertram",male,NaN,0,0,113791,26.5500,NaN,S
149,1041,2,"Lahtinen, Rev. William",male,30.00,1,1,250651,26.0000,NaN,S
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00,0,1,11767,83.1583,C54,C
151,1043,3,"Matinoff, Mr. Nicola",male,NaN,0,0,349255,7.8958,NaN,C
152,1044,3,"Storey, Mr. Thomas",male,60.50,0,0,3701,NaN,NaN,S
153,1045,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.00,0,2,350405,12.1833,NaN,S
154,1046,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.3875,NaN,S
155,1047,3,"Duquemin, Mr. Joseph",male,24.00,0,0,S.O./P.P. 752,7.5500,NaN,S
156,1048,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.7792,C97,S
157,1049,3,"Lundin, Miss. Olga Elida",female,23.00,0,0,347469,7.8542,NaN,S
158,1050,1,"Borebank, Mr. John James",male,42.00,0,0,110489,26.5500,D22,S
159,1051,3,"Peacock, Mrs. Benjamin (Edith Nile)",female,26.00,0,2,SOTON/O.Q. 3101315,13.7750,NaN,S
160,1052,3,"Smyth, Miss. Julia",female,NaN,0,0,335432,7.7333,NaN,Q
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C
162,1054,2,"Wright, Miss. Marion",female,26.00,0,0,220844,13.5000,NaN,S
163,1055,3,"Pearce, Mr. Ernest",male,NaN,0,0,343271,7.0000,NaN,S
164,1056,2,"Peruschitz, Rev. Joseph Maria",male,41.00,0,0,237393,13.0000,NaN,S
165,1057,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26.00,1,1,315153,22.0250,NaN,S
166,1058,1,"Brandeis, Mr. Emil",male,48.00,0,0,PC 17591,50.4958,B10,C
167,1059,3,"Ford, Mr. Edward Watson",male,18.00,2,2,W./C. 6608,34.3750,NaN,S
168,1060,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C
169,1061,3,"Hellstrom, Miss. Hilda Maria",female,22.00,0,0,7548,8.9625,NaN,S
170,1062,3,"Lithman, Mr. Simon",male,NaN,0,0,S.O./P.P. 251,7.5500,NaN,S
171,1063,3,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C
172,1064,3,"Dyker, Mr. Adolf Fredrik",male,23.00,1,0,347072,13.9000,NaN,S
173,1065,3,"Torfa, Mr. Assad",male,NaN,0,0,2673,7.2292,NaN,C
174,1066,3,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson",male,40.00,1,5,347077,31.3875,NaN,S
175,1067,2,"Brown, Miss. Edith Eileen",female,15.00,0,2,29750,39.0000,NaN,S
176,1068,2,"Sincock, Miss. Maude",female,20.00,0,0,C.A. 33112,36.7500,NaN,S
177,1069,1,"Stengel, Mr. Charles Emil Henry",male,54.00,1,0,11778,55.4417,C116,C
178,1070,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.00,0,3,230136,39.0000,F4,S
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.00,0,2,PC 17756,83.1583,E45,C
180,1072,2,"McCrie, Mr. James Matthew",male,30.00,0,0,233478,13.0000,NaN,S
181,1073,1,"Compton, Mr. Alexander Taylor Jr",male,37.00,1,1,PC 17756,83.1583,E52,C
182,1074,1,"Marvin, Mrs. Daniel Warner (Mary Graham Carmic...",female,18.00,1,0,113773,53.1000,D30,S
183,1075,3,"Lane, Mr. Patrick",male,NaN,0,0,7935,7.7500,NaN,Q
184,1076,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.00,1,1,PC 17558,247.5208,B58 B60,C
185,1077,2,"Maybery, Mr. Frank Hubert",male,40.00,0,0,239059,16.0000,NaN,S
186,1078,2,"Phillips, Miss. Alice Frances Louisa",female,21.00,0,1,S.O./P.P. 2,21.0000,NaN,S
187,1079,3,"Davies, Mr. Joseph",male,17.00,2,0,A/4 48873,8.0500,NaN,S
188,1080,3,"Sage, Miss. Ada",female,NaN,8,2,CA. 2343,69.5500,NaN,S
189,1081,2,"Veal, Mr. James",male,40.00,0,0,28221,13.0000,NaN,S
190,1082,2,"Angle, Mr. William A",male,34.00,1,0,226875,26.0000,NaN,S
191,1083,1,"Salomon, Mr. Abraham L",male,NaN,0,0,111163,26.0000,NaN,S
192,1084,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.5000,NaN,S
193,1085,2,"Lingane, Mr. John",male,61.00,0,0,235509,12.3500,NaN,Q
194,1086,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,NaN,S
195,1087,3,"Karlsson, Mr. Julius Konrad Eugen",male,33.00,0,0,347465,7.8542,NaN,S
196,1088,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C
197,1089,3,"Nilsson, Miss. Berta Olivia",female,18.00,0,0,347066,7.7750,NaN,S
198,1090,2,"Baimbrigge, Mr. Charles Robert",male,23.00,0,0,C.A. 31030,10.5000,NaN,S
199,1091,3,"Rasmussen, Mrs. (Lena Jacobsen Solvang)",female,NaN,0,0,65305,8.1125,NaN,S
200,1092,3,"Murphy, Miss. Nora",female,NaN,0,0,36568,15.5000,NaN,Q
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
202,1094,1,"Astor, Col. John Jacob",male,47.00,1,0,PC 17757,227.5250,C62 C64,C
203,1095,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.0000,NaN,S
204,1096,2,"Andrew, Mr. Frank Thomas",male,25.00,0,0,C.A. 34050,10.5000,NaN,S
205,1097,1,"Omont, Mr. Alfred Fernand",male,NaN,0,0,F.C. 12998,25.7417,NaN,C
206,1098,3,"McGowan, Miss. Katherine",female,35.00,0,0,9232,7.7500,NaN,Q
207,1099,2,"Collett, Mr. Sidney C Stuart",male,24.00,0,0,28034,10.5000,NaN,S
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.00,0,0,PC 17613,27.7208,A11,C
209,1101,3,"Delalic, Mr. Redjo",male,25.00,0,0,349250,7.8958,NaN,S
210,1102,3,"Andersen, Mr. Albert Karvin",male,32.00,0,0,C 4001,22.5250,NaN,S
211,1103,3,"Finoli, Mr. Luigi",male,NaN,0,0,SOTON/O.Q. 3101308,7.0500,NaN,S
212,1104,2,"Deacon, Mr. Percy William",male,17.00,0,0,S.O.C. 14879,73.5000,NaN,S
213,1105,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60.00,1,0,24065,26.0000,NaN,S
214,1106,3,"Andersson, Miss. Ida Augusta Margareta",female,38.00,4,2,347091,7.7750,NaN,S
215,1107,1,"Head, Mr. Christopher",male,42.00,0,0,113038,42.5000,B11,S
216,1108,3,"Mahon, Miss. Bridget Delia",female,NaN,0,0,330924,7.8792,NaN,Q
217,1109,1,"Wick, Mr. George Dennick",male,57.00,1,1,36928,164.8667,NaN,S
218,1110,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00,1,1,113503,211.5000,C80,C
219,1111,3,"Thomson, Mr. Alexander Morrison",male,NaN,0,0,32302,8.0500,NaN,S
220,1112,2,"Duran y More, Miss. Florentina",female,30.00,1,0,SC/PARIS 2148,13.8583,NaN,C
221,1113,3,"Reynolds, Mr. Harold J",male,21.00,0,0,342684,8.0500,NaN,S
222,1114,2,"Cook, Mrs. (Selena Rogers)",female,22.00,0,0,W./C. 14266,10.5000,F33,S
223,1115,3,"Karlsson, Mr. Einar Gervasius",male,21.00,0,0,350053,7.7958,NaN,S
224,1116,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.00,0,0,PC 17606,27.4458,NaN,C
225,1117,3,"Moubarek, Mrs. George (Omine Amenia"" Alexander)""",female,NaN,0,2,2661,15.2458,NaN,C
226,1118,3,"Asplund, Mr. Johan Charles",male,23.00,0,0,350054,7.7958,NaN,S
227,1119,3,"McNeill, Miss. Bridget",female,NaN,0,0,370368,7.7500,NaN,Q
228,1120,3,"Everett, Mr. Thomas James",male,40.50,0,0,C.A. 6212,15.1000,NaN,S
229,1121,2,"Hocking, Mr. Samuel James Metcalfe",male,36.00,0,0,242963,13.0000,NaN,S
230,1122,2,"Sweet, Mr. George Frederick",male,14.00,0,0,220845,65.0000,NaN,S
231,1123,1,"Willard, Miss. Constance",female,21.00,0,0,113795,26.5500,NaN,S
232,1124,3,"Wiklund, Mr. Karl Johan",male,21.00,1,0,3101266,6.4958,NaN,S
233,1125,3,"Linehan, Mr. Michael",male,NaN,0,0,330971,7.8792,NaN,Q
234,1126,1,"Cumings, Mr. John Bradley",male,39.00,1,0,PC 17599,71.2833,C85,C
235,1127,3,"Vendel, Mr. Olof Edvin",male,20.00,0,0,350416,7.8542,NaN,S
236,1128,1,"Warren, Mr. Frank Manley",male,64.00,1,0,110813,75.2500,D37,C
237,1129,3,"Baccos, Mr. Raffull",male,20.00,0,0,2679,7.2250,NaN,C
238,1130,2,"Hiltunen, Miss. Marta",female,18.00,1,1,250650,13.0000,NaN,S
239,1131,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.00,1,0,PC 17761,106.4250,C86,C
240,1132,1,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)",female,55.00,0,0,112377,27.7208,NaN,C
241,1133,2,"Christy, Mrs. (Alice Frances)",female,45.00,0,2,237789,30.0000,NaN,S
242,1134,1,"Spedden, Mr. Frederic Oakley",male,45.00,1,1,16966,134.5000,E34,C
243,1135,3,"Hyman, Mr. Abraham",male,NaN,0,0,3470,7.8875,NaN,S
244,1136,3,"Johnston, Master. William Arthur Willie""""",male,NaN,1,2,W./C. 6607,23.4500,NaN,S
245,1137,1,"Kenyon, Mr. Frederick R",male,41.00,1,0,17464,51.8625,D21,S
246,1138,2,"Karnes, Mrs. J Frank (Claire Bennett)",female,22.00,0,0,F.C.C. 13534,21.0000,NaN,S
247,1139,2,"Drew, Mr. James Vivian",male,42.00,1,1,28220,32.5000,NaN,S
248,1140,2,"Hold, Mrs. Stephen (Annie Margaret Hill)",female,29.00,1,0,26707,26.0000,NaN,S
249,1141,3,"Khalil, Mrs. Betros (Zahie Maria"" Elias)""",female,NaN,1,0,2660,14.4542,NaN,C
250,1142,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
251,1143,3,"Abrahamsson, Mr. Abraham August Johannes",male,20.00,0,0,SOTON/O2 3101284,7.9250,NaN,S
252,1144,1,"Clark, Mr. Walter Miller",male,27.00,1,0,13508,136.7792,C89,C
253,1145,3,"Salander, Mr. Karl Johan",male,24.00,0,0,7266,9.3250,NaN,S
254,1146,3,"Wenzel, Mr. Linhart",male,32.50,0,0,345775,9.5000,NaN,S
255,1147,3,"MacKay, Mr. George William",male,NaN,0,0,C.A. 42795,7.5500,NaN,S

In [13]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [17]:
df=df[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
df

     PassengerId  Pclass     Sex    Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.50      0      0    7.8292        Q
1            893       3  female  47.00      1      0    7.0000        S
2            894       2    male  62.00      0      0    9.6875        Q
3            895       3    male  27.00      0      0    8.6625        S
4            896       3  female  22.00      1      1   12.2875        S
5            897       3    male  14.00      0      0    9.2250        S
6            898       3  female  30.00      0      0    7.6292        Q
7            899       2    male  26.00      1      1   29.0000        S
8            900       3  female  18.00      0      0    7.2292        C
9            901       3    male  21.00      2      0   24.1500        S
10           902       3    male    NaN      0      0    7.8958        S
11           903       1    male  46.00      0      0   26.0000        S
12           904       1  female  23.00      1      0   82.2667        S
13           905       2    male  63.00      1      0   26.0000        S
14           906       1  female  47.00      1      0   61.1750        S
15           907       2  female  24.00      1      0   27.7208        C
16           908       2    male  35.00      0      0   12.3500        Q
17           909       3    male  21.00      0      0    7.2250        C
18           910       3  female  27.00      1      0    7.9250        S
19           911       3  female  45.00      0      0    7.2250        C
20           912       1    male  55.00      1      0   59.4000        C
21           913       3    male   9.00      0      1    3.1708        S
22           914       1  female    NaN      0      0   31.6833        S
23           915       1    male  21.00      0      1   61.3792        C
24           916       1  female  48.00      1      3  262.3750        C
25           917       3    male  50.00      1      0   14.5000        S
26           918       1  female  22.00      0      1   61.9792        C
27           919       3    male  22.50      0      0    7.2250        C
28           920       1    male  41.00      0      0   30.5000        S
29           921       3    male    NaN      2      0   21.6792        C
30           922       2    male  50.00      1      0   26.0000        S
31           923       2    male  24.00      2      0   31.5000        S
32           924       3  female  33.00      1      2   20.5750        S
33           925       3  female    NaN      1      2   23.4500        S
34           926       1    male  30.00      1      0   57.7500        C
35           927       3    male  18.50      0      0    7.2292        C
36           928       3  female    NaN      0      0    8.0500        S
37           929       3  female  21.00      0      0    8.6625        S
38           930       3    male  25.00      0      0    9.5000        S
39           931       3    male    NaN      0      0   56.4958        S
40           932       3    male  39.00      0      1   13.4167        C
41           933       1    male    NaN      0      0   26.5500        S
42           934       3    male  41.00      0      0    7.8500        S
43           935       2  female  30.00      0      0   13.0000        S
44           936       1  female  45.00      1      0   52.5542        S
45           937       3    male  25.00      0      0    7.9250        S
46           938       1    male  45.00      0      0   29.7000        C
47           939       3    male    NaN      0      0    7.7500        Q
48           940       1  female  60.00      0      0   76.2917        C
49           941       3  female  36.00      0      2   15.9000        S
50           942       1    male  24.00      1      0   60.0000        S
51           943       2    male  27.00      0      0   15.0333        C
52           944       2  female  20.00      2      1   23.0000        S
53           945       1  female  28.00      3      2  263.0000        S
54           946       2    male    NaN      0      0   15.5792        C
55           947       3    male  10.00      4      1   29.1250        Q
56           948       3    male  35.00      0      0    7.8958        S
57           949       3    male  25.00      0      0    7.6500        S
58           950       3    male    NaN      1      0   16.1000        S
59           951       1  female  36.00      0      0  262.3750        C
60           952       3    male  17.00      0      0    7.8958        S
61           953       2    male  32.00      0      0   13.5000        S
62           954       3    male  18.00      0      0    7.7500        S
63           955       3  female  22.00      0      0    7.7250        Q
64           956       1    male  13.00      2      2  262.3750        C
65           957       2  female    NaN      0      0   21.0000        S
66           958       3  female  18.00      0      0    7.8792        Q
67           959       1    male  47.00      0      0   42.4000        S
68           960       1    male  31.00      0      0   28.5375        C
69           961       1  female  60.00      1      4  263.0000        S
70           962       3  female  24.00      0      0    7.7500        Q
71           963       3    male  21.00      0      0    7.8958        S
72           964       3  female  29.00      0      0    7.9250        S
73           965       1    male  28.50      0      0   27.7208        C
74           966       1  female  35.00      0      0  211.5000        C
75           967       1    male  32.50      0      0  211.5000        C
76           968       3    male    NaN      0      0    8.0500        S
77           969       1  female  55.00      2      0   25.7000        S
78           970       2    male  30.00      0      0   13.0000        S
79           971       3  female  24.00      0      0    7.7500        Q
80           972       3    male   6.00      1      1   15.2458        C
81           973       1    male  67.00      1      0  221.7792        S
82           974       1    male  49.00      0      0   26.0000        S
83           975       3    male    NaN      0      0    7.8958        S
84           976       2    male    NaN      0      0   10.7083        Q
85           977       3    male    NaN      1      0   14.4542        C
86           978       3  female  27.00      0      0    7.8792        Q
87           979       3  female  18.00      0      0    8.0500        S
88           980       3  female    NaN      0      0    7.7500        Q
89           981       2    male   2.00      1      1   23.0000        S
90           982       3  female  22.00      1      0   13.9000        S
91           983       3    male    NaN      0      0    7.7750        S
92           984       1  female  27.00      1      2   52.0000        S
93           985       3    male    NaN      0      0    8.0500        S
94           986       1    male  25.00      0      0   26.0000        C
95           987       3    male  25.00      0      0    7.7958        S
96           988       1  female  76.00      1      0   78.8500        S
97           989       3    male  29.00      0      0    7.9250        S
98           990       3  female  20.00      0      0    7.8542        S
99           991       3    male  33.00      0      0    8.0500        S
100          992       1  female  43.00      1      0   55.4417        C
101          993       2    male  27.00      1      0   26.0000        S
102          994       3    male    NaN      0      0    7.7500        Q
103          995       3    male  26.00      0      0    7.7750        S
104          996       3  female  16.00      1      1    8.5167        C
105          997       3    male  28.00      0      0   22.5250        S
106          998       3    male  21.00      0      0    7.8208        Q
107          999       3    male    NaN      0      0    7.7500        Q
108         1000       3    male    NaN      0      0    8.7125        S
109         1001       2    male  18.50      0      0   13.0000        S
110         1002       2    male  41.00      0      0   15.0458        C
111         1003       3  female    NaN      0      0    7.7792        Q
112         1004       1  female  36.00      0      0   31.6792        C
113         1005       3  female  18.50      0      0    7.2833        Q
114         1006       1  female  63.00      1      0  221.7792        S
115         1007       3    male  18.00      1      0   14.4542        C
116         1008       3    male    NaN      0      0    6.4375        C
117         1009       3  female   1.00      1      1   16.7000        S
118         1010       1    male  36.00      0      0   75.2417        C
119         1011       2  female  29.00      1      0   26.0000        S
120         1012       2  female  12.00      0      0   15.7500        S
121         1013       3    male    NaN      1      0    7.7500        Q
122         1014       1  female  35.00      1      0   57.7500        C
123         1015       3    male  28.00      0      0    7.2500        S
124         1016       3    male    NaN      0      0    7.7500        Q
125         1017       3  female  17.00      0      1   16.1000        S
126         1018       3    male  22.00      0      0    7.7958        S
127         1019       3  female    NaN      2      0   23.2500        Q
128         1020       2    male  42.00      0      0   13.0000        S
129         1021       3    male  24.00      0      0    8.0500        S
130         1022       3    male  32.00      0      0    8.0500        S
131         1023       1    male  53.00      0      0   28.5000        C
132         1024       3  female    NaN      0      4   25.4667        S
133         1025       3    male    NaN      1      0    6.4375        C
134         1026       3    male  43.00      0      0    7.8958        S
135         1027       3    male  24.00      0      0    7.8542        S
136         1028       3    male  26.50      0      0    7.2250        C
137         1029       2    male  26.00      0      0   13.0000        S
138         1030       3  female  23.00      0      0    8.0500        S
139         1031       3    male  40.00      1      6   46.9000        S
140         1032       3  female  10.00      5      2   46.9000        S
141         1033       1  female  33.00      0      0  151.5500        S
142         1034       1    male  61.00      1      3  262.3750        C
143         1035       2    male  28.00      0      0   26.0000        S
144         1036       1    male  42.00      0      0   26.5500        S
145         1037       3    male  31.00      3      0   18.0000        S
146         1038       1    male    NaN      0      0   51.8625        S
147         1039       3    male  22.00      0      0    8.0500        S
148         1040       1    male    NaN      0      0   26.5500        S
149         1041       2    male  30.00      1      1   26.0000        S
150         1042       1  female  23.00      0      1   83.1583        C
151         1043       3    male    NaN      0      0    7.8958        C
152         1044       3    male  60.50      0      0       NaN        S
153         1045       3  female  36.00      0      2   12.1833        S
154         1046       3    male  13.00      4      2   31.3875        S
155         1047       3    male  24.00      0      0    7.5500        S
156         1048       1  female  29.00      0      0  221.7792        S
157         1049       3  female  23.00      0      0    7.8542        S
158         1050       1    male  42.00      0      0   26.5500        S
159         1051       3  female  26.00      0      2   13.7750        S
160         1052       3  female    NaN      0      0    7.7333        Q
161         1053       3    male   7.00      1      1   15.2458        C
162         1054       2  female  26.00      0      0   13.5000        S
163         1055       3    male    NaN      0      0    7.0000        S
164         1056       2    male  41.00      0      0   13.0000        S
165         1057       3  female  26.00      1      1   22.0250        S
166         1058       1    male  48.00      0      0   50.4958        C
167         1059       3    male  18.00      2      2   34.3750        S
168         1060       1  female    NaN      0      0   27.7208        C
169         1061       3  female  22.00      0      0    8.9625        S
170         1062       3    male    NaN      0      0    7.5500        S
171         1063       3    male  27.00      0      0    7.2250        C
172         1064       3    male  23.00      1      0   13.9000        S
173         1065       3    male    NaN      0      0    7.2292        C
174         1066       3    male  40.00      1      5   31.3875        S
175         1067       2  female  15.00      0      2   39.0000        S
176         1068       2  female  20.00      0      0   36.7500        S
177         1069       1    male  54.00      1      0   55.4417        C
178         1070       2  female  36.00      0      3   39.0000        S
179         1071       1  female  64.00      0      2   83.1583        C
180         1072       2    male  30.00      0      0   13.0000        S
181         1073       1    male  37.00      1      1   83.1583        C
182         1074       1  female  18.00      1      0   53.1000        S
183         1075       3    male    NaN      0      0    7.7500        Q
184         1076       1  female  27.00      1      1  247.5208        C
185         1077       2    male  40.00      0      0   16.0000        S
186         1078       2  female  21.00      0      1   21.0000        S
187         1079       3    male  17.00      2      0    8.0500        S
188         1080       3  female    NaN      8      2   69.5500        S
189         1081       2    male  40.00      0      0   13.0000        S
190         1082       2    male  34.00      1      0   26.0000        S
191         1083       1    male    NaN      0      0   26.0000        S
192         1084       3    male  11.50      1      1   14.5000        S
193         1085       2    male  61.00      0      0   12.3500        Q
194         1086       2    male   8.00      0      2   32.5000        S
195         1087       3    male  33.00      0      0    7.8542        S
196         1088       1    male   6.00      0      2  134.5000        C
197         1089       3  female  18.00      0      0    7.7750        S
198         1090       2    male  23.00      0      0   10.5000        S
199         1091       3  female    NaN      0      0    8.1125        S
200         1092       3  female    NaN      0      0   15.5000        Q
201         1093       3    male   0.33      0      2   14.4000        S
202         1094       1    male  47.00      1      0  227.5250        C
203         1095       2  female   8.00      1      1   26.0000        S
204         1096       2    male  25.00      0      0   10.5000        S
205         1097       1    male    NaN      0      0   25.7417        C
206         1098       3  female  35.00      0      0    7.7500        Q
207         1099       2    male  24.00      0      0   10.5000        S
208         1100       1  female  33.00      0      0   27.7208        C
209         1101       3    male  25.00      0      0    7.8958        S
210         1102       3    male  32.00      0      0   22.5250        S
211         1103       3    male    NaN      0      0    7.0500        S
212         1104       2    male  17.00      0      0   73.5000        S
213         1105       2  female  60.00      1      0   26.0000        S
214         1106       3  female  38.00      4      2    7.7750        S
215         1107       1    male  42.00      0      0   42.5000        S
216         1108       3  female    NaN      0      0    7.8792        Q
217         1109       1    male  57.00      1      1  164.8667        S
218         1110       1  female  50.00      1      1  211.5000        C
219         1111       3    male    NaN      0      0    8.0500        S
220         1112       2  female  30.00      1      0   13.8583        C
221         1113       3    male  21.00      0      0    8.0500        S
222         1114       2  female  22.00      0      0   10.5000        S
223         1115       3    male  21.00      0      0    7.7958        S
224         1116       1  female  53.00      0      0   27.4458        C
225         1117       3  female    NaN      0      2   15.2458        C
226         1118       3    male  23.00      0      0    7.7958        S
227         1119       3  female    NaN      0      0    7.7500        Q
228         1120       3    male  40.50      0      0   15.1000        S
229         1121       2    male  36.00      0      0   13.0000        S
230         1122       2    male  14.00      0      0   65.0000        S
231         1123       1  female  21.00      0      0   26.5500        S
232         1124       3    male  21.00      1      0    6.4958        S
233         1125       3    male    NaN      0      0    7.8792        Q
234         1126       1    male  39.00      1      0   71.2833        C
235         1127       3    male  20.00      0      0    7.8542        S
236         1128       1    male  64.00      1      0   75.2500        C
237         1129       3    male  20.00      0      0    7.2250        C
238         1130       2  female  18.00      1      1   13.0000        S
239         1131       1  female  48.00      1      0  106.4250        C
240         1132       1  female  55.00      0      0   27.7208        C
241         1133       2  female  45.00      0      2   30.0000        S
242         1134       1    male  45.00      1      1  134.5000        C
243         1135       3    male    NaN      0      0    7.8875        S
244         1136       3    male    NaN      1      2   23.4500        S
245         1137       1    male  41.00      1      0   51.8625        S
246         1138       2  female  22.00      0      0   21.0000        S
247         1139       2    male  42.00      1      1   32.5000        S
248         1140       2  female  29.00      1      0   26.0000        S
249         1141       3  female    NaN      1      0   14.4542        C
250         1142       2  female   0.92      1      2   27.7500        S
251         1143       3    male  20.00      0      0    7.9250        S
252         1144       1    male  27.00      1      0  136.7792        C
253         1145       3    male  24.00      0      0    9.3250        S
254         1146       3    male  32.50      0      0    9.5000        S
255         1147       3    male    NaN      0      0    7.5500        S
256         1148       3    male    NaN      0      0    7.7500        Q
257         1149       3    male  28.00      0      0    8.0500        S
258         1150       2  female  19.00      0      0   13.0000        S
259         1151       3    male  21.00      0      0    7.7750        S
260         1152       3    male  36.50      1      0   17.4000        S
261         1153       3    male  21.00      0      0    7.8542        S
262         1154       2  female  29.00      0      2   23.0000        S
263         1155       3  female   1.00      1      1   12.1833        S
264         1156       2    male  30.00      0      0   12.7375        C
265         1157       3    male    NaN      0      0    7.8958        S
266         1158       1    male    NaN      0      0    0.0000        S
267         1159       3    male    NaN      0      0    7.5500        S
268         1160       3  female    NaN      0      0    8.0500        S
269         1161       3    male  17.00      0      0    8.6625        S
270         1162       1    male  46.00      0      0   75.2417        C
271         1163       3    male    NaN      0      0    7.7500        Q

In [26]:
df.fillna({'Age':0})

In [27]:
df.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
dtype: int64

In [28]:
for feat in ["Sex", "Embarked"]:
#     x = pd.get_dummies(df["Age"] // 6)
#     x = pd.get_dummies(pd.cut(df['Age'],5))
    x = pd.get_dummies(df[feat], prefix=feat)   #prefix:列的前缀名
    df = pd.concat([df, x], axis=1)    #数据合并
    #df[feat] = pd.get_dummies(df[feat], prefix=feat)
    
df.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,3,male,34.5,0,0,7.8292,Q,0,1,0,1,0
1,893,3,female,47.0,1,0,7.0000,S,1,0,0,0,1
2,894,2,male,62.0,0,0,9.6875,Q,0,1,0,1,0
3,895,3,male,27.0,0,0,8.6625,S,0,1,0,0,1
4,896,3,female,22.0,1,1,12.2875,S,1,0,0,0,1

In [29]:
df=df[['PassengerId','Pclass','Age','SibSp','Parch','Fare','Sex_female','Sex_male','Embarked_C','Embarked_Q','Embarked_S']]
df

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,3,34.50,0,0,7.8292,0,1,0,1,0
1,893,3,47.00,1,0,7.0000,1,0,0,0,1
2,894,2,62.00,0,0,9.6875,0,1,0,1,0
3,895,3,27.00,0,0,8.6625,0,1,0,0,1
4,896,3,22.00,1,1,12.2875,1,0,0,0,1
5,897,3,14.00,0,0,9.2250,0,1,0,0,1
6,898,3,30.00,0,0,7.6292,1,0,0,1,0
7,899,2,26.00,1,1,29.0000,0,1,0,0,1
8,900,3,18.00,0,0,7.2292,1,0,1,0,0
9,901,3,21.00,2,0,24.1500,0,1,0,0,1
10,902,3,0.00,0,0,7.8958,0,1,0,0,1
11,903,1,46.00,0,0,26.0000,0,1,0,0,1
12,904,1,23.00,1,0,82.2667,1,0,0,0,1
13,905,2,63.00,1,0,26.0000,0,1,0,0,1
14,906,1,47.00,1,0,61.1750,1,0,0,0,1
15,907,2,24.00,1,0,27.7208,1,0,1,0,0
16,908,2,35.00,0,0,12.3500,0,1,0,1,0
17,909,3,21.00,0,0,7.2250,0,1,1,0,0
18,910,3,27.00,1,0,7.9250,1,0,0,0,1
19,911,3,45.00,0,0,7.2250,1,0,1,0,0
20,912,1,55.00,1,0,59.4000,0,1,1,0,0
21,913,3,9.00,0,1,3.1708,0,1,0,0,1
22,914,1,0.00,0,0,31.6833,1,0,0,0,1
23,915,1,21.00,0,1,61.3792,0,1,1,0,0
24,916,1,48.00,1,3,262.3750,1,0,1,0,0
25,917,3,50.00,1,0,14.5000,0,1,0,0,1
26,918,1,22.00,0,1,61.9792,1,0,1,0,0
27,919,3,22.50,0,0,7.2250,0,1,1,0,0
28,920,1,41.00,0,0,30.5000,0,1,0,0,1
29,921,3,0.00,2,0,21.6792,0,1,1,0,0
30,922,2,50.00,1,0,26.0000,0,1,0,0,1
31,923,2,24.00,2,0,31.5000,0,1,0,0,1
32,924,3,33.00,1,2,20.5750,1,0,0,0,1
33,925,3,0.00,1,2,23.4500,1,0,0,0,1
34,926,1,30.00,1,0,57.7500,0,1,1,0,0
35,927,3,18.50,0,0,7.2292,0,1,1,0,0
36,928,3,0.00,0,0,8.0500,1,0,0,0,1
37,929,3,21.00,0,0,8.6625,1,0,0,0,1
38,930,3,25.00,0,0,9.5000,0,1,0,0,1
39,931,3,0.00,0,0,56.4958,0,1,0,0,1
40,932,3,39.00,0,1,13.4167,0,1,1,0,0
41,933,1,0.00,0,0,26.5500,0,1,0,0,1
42,934,3,41.00,0,0,7.8500,0,1,0,0,1
43,935,2,30.00,0,0,13.0000,1,0,0,0,1
44,936,1,45.00,1,0,52.5542,1,0,0,0,1
45,937,3,25.00,0,0,7.9250,0,1,0,0,1
46,938,1,45.00,0,0,29.7000,0,1,1,0,0
47,939,3,0.00,0,0,7.7500,0,1,0,1,0
48,940,1,60.00,0,0,76.2917,1,0,1,0,0
49,941,3,36.00,0,2,15.9000,1,0,0,0,1
50,942,1,24.00,1,0,60.0000,0,1,0,0,1
51,943,2,27.00,0,0,15.0333,0,1,1,0,0
52,944,2,20.00,2,1,23.0000,1,0,0,0,1
53,945,1,28.00,3,2,263.0000,1,0,0,0,1
54,946,2,0.00,0,0,15.5792,0,1,1,0,0
55,947,3,10.00,4,1,29.1250,0,1,0,1,0
56,948,3,35.00,0,0,7.8958,0,1,0,0,1
57,949,3,25.00,0,0,7.6500,0,1,0,0,1
58,950,3,0.00,1,0,16.1000,0,1,0,0,1
59,951,1,36.00,0,0,262.3750,1,0,1,0,0
60,952,3,17.00,0,0,7.8958,0,1,0,0,1
61,953,2,32.00,0,0,13.5000,0,1,0,0,1
62,954,3,18.00,0,0,7.7500,0,1,0,0,1
63,955,3,22.00,0,0,7.7250,1,0,0,1,0
64,956,1,13.00,2,2,262.3750,0,1,1,0,0
65,957,2,0.00,0,0,21.0000,1,0,0,0,1
66,958,3,18.00,0,0,7.8792,1,0,0,1,0
67,959,1,47.00,0,0,42.4000,0,1,0,0,1
68,960,1,31.00,0,0,28.5375,0,1,1,0,0
69,961,1,60.00,1,4,263.0000,1,0,0,0,1
70,962,3,24.00,0,0,7.7500,1,0,0,1,0
71,963,3,21.00,0,0,7.8958,0,1,0,0,1
72,964,3,29.00,0,0,7.9250,1,0,0,0,1
73,965,1,28.50,0,0,27.7208,0,1,1,0,0
74,966,1,35.00,0,0,211.5000,1,0,1,0,0
75,967,1,32.50,0,0,211.5000,0,1,1,0,0
76,968,3,0.00,0,0,8.0500,0,1,0,0,1
77,969,1,55.00,2,0,25.7000,1,0,0,0,1
78,970,2,30.00,0,0,13.0000,0,1,0,0,1
79,971,3,24.00,0,0,7.7500,1,0,0,1,0
80,972,3,6.00,1,1,15.2458,0,1,1,0,0
81,973,1,67.00,1,0,221.7792,0,1,0,0,1
82,974,1,49.00,0,0,26.0000,0,1,0,0,1
83,975,3,0.00,0,0,7.8958,0,1,0,0,1
84,976,2,0.00,0,0,10.7083,0,1,0,1,0
85,977,3,0.00,1,0,14.4542,0,1,1,0,0
86,978,3,27.00,0,0,7.8792,1,0,0,1,0
87,979,3,18.00,0,0,8.0500,1,0,0,0,1
88,980,3,0.00,0,0,7.7500,1,0,0,1,0
89,981,2,2.00,1,1,23.0000,0,1,0,0,1
90,982,3,22.00,1,0,13.9000,1,0,0,0,1
91,983,3,0.00,0,0,7.7750,0,1,0,0,1
92,984,1,27.00,1,2,52.0000,1,0,0,0,1
93,985,3,0.00,0,0,8.0500,0,1,0,0,1
94,986,1,25.00,0,0,26.0000,0,1,1,0,0
95,987,3,25.00,0,0,7.7958,0,1,0,0,1
96,988,1,76.00,1,0,78.8500,1,0,0,0,1
97,989,3,29.00,0,0,7.9250,0,1,0,0,1
98,990,3,20.00,0,0,7.8542,1,0,0,0,1
99,991,3,33.00,0,0,8.0500,0,1,0,0,1
100,992,1,43.00,1,0,55.4417,1,0,1,0,0
101,993,2,27.00,1,0,26.0000,0,1,0,0,1
102,994,3,0.00,0,0,7.7500,0,1,0,1,0
103,995,3,26.00,0,0,7.7750,0,1,0,0,1
104,996,3,16.00,1,1,8.5167,1,0,1,0,0
105,997,3,28.00,0,0,22.5250,0,1,0,0,1
106,998,3,21.00,0,0,7.8208,0,1,0,1,0
107,999,3,0.00,0,0,7.7500,0,1,0,1,0
108,1000,3,0.00,0,0,8.7125,0,1,0,0,1
109,1001,2,18.50,0,0,13.0000,0,1,0,0,1
110,1002,2,41.00,0,0,15.0458,0,1,1,0,0
111,1003,3,0.00,0,0,7.7792,1,0,0,1,0
112,1004,1,36.00,0,0,31.6792,1,0,1,0,0
113,1005,3,18.50,0,0,7.2833,1,0,0,1,0
114,1006,1,63.00,1,0,221.7792,1,0,0,0,1
115,1007,3,18.00,1,0,14.4542,0,1,1,0,0
116,1008,3,0.00,0,0,6.4375,0,1,1,0,0
117,1009,3,1.00,1,1,16.7000,1,0,0,0,1
118,1010,1,36.00,0,0,75.2417,0,1,1,0,0
119,1011,2,29.00,1,0,26.0000,1,0,0,0,1
120,1012,2,12.00,0,0,15.7500,1,0,0,0,1
121,1013,3,0.00,1,0,7.7500,0,1,0,1,0
122,1014,1,35.00,1,0,57.7500,1,0,1,0,0
123,1015,3,28.00,0,0,7.2500,0,1,0,0,1
124,1016,3,0.00,0,0,7.7500,0,1,0,1,0
125,1017,3,17.00,0,1,16.1000,1,0,0,0,1
126,1018,3,22.00,0,0,7.7958,0,1,0,0,1
127,1019,3,0.00,2,0,23.2500,1,0,0,1,0
128,1020,2,42.00,0,0,13.0000,0,1,0,0,1
129,1021,3,24.00,0,0,8.0500,0,1,0,0,1
130,1022,3,32.00,0,0,8.0500,0,1,0,0,1
131,1023,1,53.00,0,0,28.5000,0,1,1,0,0
132,1024,3,0.00,0,4,25.4667,1,0,0,0,1
133,1025,3,0.00,1,0,6.4375,0,1,1,0,0
134,1026,3,43.00,0,0,7.8958,0,1,0,0,1
135,1027,3,24.00,0,0,7.8542,0,1,0,0,1
136,1028,3,26.50,0,0,7.2250,0,1,1,0,0
137,1029,2,26.00,0,0,13.0000,0,1,0,0,1
138,1030,3,23.00,0,0,8.0500,1,0,0,0,1
139,1031,3,40.00,1,6,46.9000,0,1,0,0,1
140,1032,3,10.00,5,2,46.9000,1,0,0,0,1
141,1033,1,33.00,0,0,151.5500,1,0,0,0,1
142,1034,1,61.00,1,3,262.3750,0,1,1,0,0
143,1035,2,28.00,0,0,26.0000,0,1,0,0,1
144,1036,1,42.00,0,0,26.5500,0,1,0,0,1
145,1037,3,31.00,3,0,18.0000,0,1,0,0,1
146,1038,1,0.00,0,0,51.8625,0,1,0,0,1
147,1039,3,22.00,0,0,8.0500,0,1,0,0,1
148,1040,1,0.00,0,0,26.5500,0,1,0,0,1
149,1041,2,30.00,1,1,26.0000,0,1,0,0,1
150,1042,1,23.00,0,1,83.1583,1,0,1,0,0
151,1043,3,0.00,0,0,7.8958,0,1,1,0,0
152,1044,3,60.50,0,0,NaN,0,1,0,0,1
153,1045,3,36.00,0,2,12.1833,1,0,0,0,1
154,1046,3,13.00,4,2,31.3875,0,1,0,0,1
155,1047,3,24.00,0,0,7.5500,0,1,0,0,1
156,1048,1,29.00,0,0,221.7792,1,0,0,0,1
157,1049,3,23.00,0,0,7.8542,1,0,0,0,1
158,1050,1,42.00,0,0,26.5500,0,1,0,0,1
159,1051,3,26.00,0,2,13.7750,1,0,0,0,1
160,1052,3,0.00,0,0,7.7333,1,0,0,1,0
161,1053,3,7.00,1,1,15.2458,0,1,1,0,0
162,1054,2,26.00,0,0,13.5000,1,0,0,0,1
163,1055,3,0.00,0,0,7.0000,0,1,0,0,1
164,1056,2,41.00,0,0,13.0000,0,1,0,0,1
165,1057,3,26.00,1,1,22.0250,1,0,0,0,1
166,1058,1,48.00,0,0,50.4958,0,1,1,0,0
167,1059,3,18.00,2,2,34.3750,0,1,0,0,1
168,1060,1,0.00,0,0,27.7208,1,0,1,0,0
169,1061,3,22.00,0,0,8.9625,1,0,0,0,1
170,1062,3,0.00,0,0,7.5500,0,1,0,0,1
171,1063,3,27.00,0,0,7.2250,0,1,1,0,0
172,1064,3,23.00,1,0,13.9000,0,1,0,0,1
173,1065,3,0.00,0,0,7.2292,0,1,1,0,0
174,1066,3,40.00,1,5,31.3875,0,1,0,0,1
175,1067,2,15.00,0,2,39.0000,1,0,0,0,1
176,1068,2,20.00,0,0,36.7500,1,0,0,0,1
177,1069,1,54.00,1,0,55.4417,0,1,1,0,0
178,1070,2,36.00,0,3,39.0000,1,0,0,0,1
179,1071,1,64.00,0,2,83.1583,1,0,1,0,0
180,1072,2,30.00,0,0,13.0000,0,1,0,0,1
181,1073,1,37.00,1,1,83.1583,0,1,1,0,0
182,1074,1,18.00,1,0,53.1000,1,0,0,0,1
183,1075,3,0.00,0,0,7.7500,0,1,0,1,0
184,1076,1,27.00,1,1,247.5208,1,0,1,0,0
185,1077,2,40.00,0,0,16.0000,0,1,0,0,1
186,1078,2,21.00,0,1,21.0000,1,0,0,0,1
187,1079,3,17.00,2,0,8.0500,0,1,0,0,1
188,1080,3,0.00,8,2,69.5500,1,0,0,0,1
189,1081,2,40.00,0,0,13.0000,0,1,0,0,1
190,1082,2,34.00,1,0,26.0000,0,1,0,0,1
191,1083,1,0.00,0,0,26.0000,0,1,0,0,1
192,1084,3,11.50,1,1,14.5000,0,1,0,0,1
193,1085,2,61.00,0,0,12.3500,0,1,0,1,0
194,1086,2,8.00,0,2,32.5000,0,1,0,0,1
195,1087,3,33.00,0,0,7.8542,0,1,0,0,1
196,1088,1,6.00,0,2,134.5000,0,1,1,0,0
197,1089,3,18.00,0,0,7.7750,1,0,0,0,1
198,1090,2,23.00,0,0,10.5000,0,1,0,0,1
199,1091,3,0.00,0,0,8.1125,1,0,0,0,1
200,1092,3,0.00,0,0,15.5000,1,0,0,1,0
201,1093,3,0.33,0,2,14.4000,0,1,0,0,1
202,1094,1,47.00,1,0,227.5250,0,1,1,0,0
203,1095,2,8.00,1,1,26.0000,1,0,0,0,1
204,1096,2,25.00,0,0,10.5000,0,1,0,0,1
205,1097,1,0.00,0,0,25.7417,0,1,1,0,0
206,1098,3,35.00,0,0,7.7500,1,0,0,1,0
207,1099,2,24.00,0,0,10.5000,0,1,0,0,1
208,1100,1,33.00,0,0,27.7208,1,0,1,0,0
209,1101,3,25.00,0,0,7.8958,0,1,0,0,1
210,1102,3,32.00,0,0,22.5250,0,1,0,0,1
211,1103,3,0.00,0,0,7.0500,0,1,0,0,1
212,1104,2,17.00,0,0,73.5000,0,1,0,0,1
213,1105,2,60.00,1,0,26.0000,1,0,0,0,1
214,1106,3,38.00,4,2,7.7750,1,0,0,0,1
215,1107,1,42.00,0,0,42.5000,0,1,0,0,1
216,1108,3,0.00,0,0,7.8792,1,0,0,1,0
217,1109,1,57.00,1,1,164.8667,0,1,0,0,1
218,1110,1,50.00,1,1,211.5000,1,0,1,0,0
219,1111,3,0.00,0,0,8.0500,0,1,0,0,1
220,1112,2,30.00,1,0,13.8583,1,0,1,0,0
221,1113,3,21.00,0,0,8.0500,0,1,0,0,1
222,1114,2,22.00,0,0,10.5000,1,0,0,0,1
223,1115,3,21.00,0,0,7.7958,0,1,0,0,1
224,1116,1,53.00,0,0,27.4458,1,0,1,0,0
225,1117,3,0.00,0,2,15.2458,1,0,1,0,0
226,1118,3,23.00,0,0,7.7958,0,1,0,0,1
227,1119,3,0.00,0,0,7.7500,1,0,0,1,0
228,1120,3,40.50,0,0,15.1000,0,1,0,0,1
229,1121,2,36.00,0,0,13.0000,0,1,0,0,1
230,1122,2,14.00,0,0,65.0000,0,1,0,0,1
231,1123,1,21.00,0,0,26.5500,1,0,0,0,1
232,1124,3,21.00,1,0,6.4958,0,1,0,0,1
233,1125,3,0.00,0,0,7.8792,0,1,0,1,0
234,1126,1,39.00,1,0,71.2833,0,1,1,0,0
235,1127,3,20.00,0,0,7.8542,0,1,0,0,1
236,1128,1,64.00,1,0,75.2500,0,1,1,0,0
237,1129,3,20.00,0,0,7.2250,0,1,1,0,0
238,1130,2,18.00,1,1,13.0000,1,0,0,0,1
239,1131,1,48.00,1,0,106.4250,1,0,1,0,0
240,1132,1,55.00,0,0,27.7208,1,0,1,0,0
241,1133,2,45.00,0,2,30.0000,1,0,0,0,1
242,1134,1,45.00,1,1,134.5000,0,1,1,0,0
243,1135,3,0.00,0,0,7.8875,0,1,0,0,1
244,1136,3,0.00,1,2,23.4500,0,1,0,0,1
245,1137,1,41.00,1,0,51.8625,0,1,0,0,1
246,1138,2,22.00,0,0,21.0000,1,0,0,0,1
247,1139,2,42.00,1,1,32.5000,0,1,0,0,1
248,1140,2,29.00,1,0,26.0000,1,0,0,0,1
249,1141,3,0.00,1,0,14.4542,1,0,1,0,0
250,1142,2,0.92,1,2,27.7500,1,0,0,0,1
251,1143,3,20.00,0,0,7.9250,0,1,0,0,1
252,1144,1,27.00,1,0,136.7792,0,1,1,0,0
253,1145,3,24.00,0,0,9.3250,0,1,0,0,1
254,1146,3,32.50,0,0,9.5000,0,1,0,0,1
255,1147,3,0.00,0,0,7.5500,0,1,0,0,1
256,1148,3,0.00,0,0,7.7500,0,1,0,1,0
257,1149,3,28.00,0,0,8.0500,0,1,0,0,1
258,1150,2,19.00,0,0,13.0000,1,0,0,0,1
259,1151,3,21.00,0,0,7.7750,0,1,0,0,1
260,1152,3,36.50,1,0,17.4000,0,1,0,0,1
261,1153,3,21.00,0,0,7.8542,0,1,0,0,1
262,1154,2,29.00,0,2,23.0000,1,0,0,0,1
263,1155,3,1.00,1,1,12.1833,1,0,0,0,1
264,1156,2,30.00,0,0,12.7375,0,1,1,0,0
265,1157,3,0.00,0,0,7.8958,0,1,0,0,1
266,1158,1,0.00,0,0,0.0000,0,1,0,0,1
267,1159,3,0.00,0,0,7.5500,0,1,0,0,1
268,1160,3,0.00,0,0,8.0500,1,0,0,0,1
269,1161,3,17.00,0,0,8.6625,0,1,0,0,1
270,1162,1,46.00,0,0,75.2417,0,1,1,0,0
271,1163,3,0.00,0,0,7.7500,0,1,0,1,0
272,1164,1,26.00,1,0,136.7792,1,0,1,0,0
273,1165,3,0.00,1,0,15.5000,1,0,0,1,0
274,1166,3,0.00,0,0,7.2250,0,1,1,0,0
275,1167,2,20.00,1,0,26.0000,1,0,0,0,1
276,1168,2,28.00,0,0,10.5000,0,1,0,0,1
277,1169,2,40.00,1,0,26.0000,0,1,0,0,1
278,1170,2,30.00,1,0,21.0000,0,1,0,0,1
279,1171,2,22.00,0,0,10.5000,0,1,0,0,1
280,1172,3,23.00,0,0,8.6625,1,0,0,0,1
281,1173,3,0.75,1,1,13.7750,0,1,0,0,1
282,1174,3,0.00,0,0,7.7500,1,0,0,1,0
283,1175,3,9.00,1,1,15.2458,1,0,1,0,0
284,1176,3,2.00,1,1,20.2125,1,0,0,0,1
285,1177,3,36.00,0,0,7.2500,0,1,0,0,1
286,1178,3,0.00,0,0,7.2500,0,1,0,0,1
287,1179,1,24.00,1,0,82.2667,0,1,0,0,1
288,1180,3,0.00,0,0,7.2292,0,1,1,0,0
289,1181,3,0.00,0,0,8.0500,0,1,0,0,1
290,1182,1,0.00,0,0,39.6000,0,1,0,0,1
291,1183,3,30.00,0,0,6.9500,1,0,0,1,0
292,1184,3,0.00,0,0,7.2292,0,1,1,0,0
293,1185,1,53.00,1,1,81.8583,0,1,0,0,1
294,1186,3,36.00,0,0,9.5000,0,1,0,0,1
295,1187,3,26.00,0,0,7.8958,0,1,0,0,1
296,1188,2,1.00,1,2,41.5792,1,0,1,0,0
297,1189,3,0.00,2,0,21.6792,0,1,1,0,0
298,1190,1,30.00,0,0,45.5000,0,1,0,0,1
299,1191,3,29.00,0,0,7.8542,0,1,0,0,1
300,1192,3,32.00,0,0,7.7750,0,1,0,0,1
301,1193,2,0.00,0,0,15.0458,0,1,1,0,0
302,1194,2,43.00,0,1,21.0000,0,1,0,0,1
303,1195,3,24.00,0,0,8.6625,0,1,0,0,1
304,1196,3,0.00,0,0,7.7500,1,0,0,1,0
305,1197,1,64.00,1,1,26.5500,1,0,0,0,1
306,1198,1,30.00,1,2,151.5500,0,1,0,0,1
307,1199,3,0.83,0,1,9.3500,0,1,0,0,1
308,1200,1,55.00,1,1,93.5000,0,1,0,0,1
309,1201,3,45.00,1,0,14.1083,1,0,0,0,1
310,1202,3,18.00,0,0,8.6625,0,1,0,0,1
311,1203,3,22.00,0,0,7.2250,0,1,1,0,0
312,1204,3,0.00,0,0,7.5750,0,1,0,0,1
313,1205,3,37.00,0,0,7.7500,1,0,0,1,0
314,1206,1,55.00,0,0,135.6333,1,0,1,0,0
315,1207,3,17.00,0,0,7.7333,1,0,0,1,0
316,1208,1,57.00,1,0,146.5208,0,1,1,0,0
317,1209,2,19.00,0,0,10.5000,0,1,0,0,1
318,1210,3,27.00,0,0,7.8542,0,1,0,0,1
319,1211,2,22.00,2,0,31.5000,0,1,0,0,1
320,1212,3,26.00,0,0,7.7750,0,1,0,0,1
321,1213,3,25.00,0,0,7.2292,0,1,1,0,0
322,1214,2,26.00,0,0,13.0000,0,1,0,0,1
323,1215,1,33.00,0,0,26.5500,0,1,0,0,1
324,1216,1,39.00,0,0,211.3375,1,0,0,0,1
325,1217,3,23.00,0,0,7.0500,0,1,0,0,1
326,1218,2,12.00,2,1,39.0000,1,0,0,0,1
327,1219,1,46.00,0,0,79.2000,0,1,1,0,0
328,1220,2,29.00,1,0,26.0000,0,1,0,0,1
329,1221,2,21.00,0,0,13.0000,0,1,0,0,1
330,1222,2,48.00,0,2,36.7500,1,0,0,0,1
331,1223,1,39.00,0,0,29.7000,0,1,1,0,0
332,1224,3,0.00,0,0,7.2250,0,1,1,0,0
333,1225,3,19.00,1,1,15.7417,1,0,1,0,0
334,1226,3,27.00,0,0,7.8958,0,1,0,0,1
335,1227,1,30.00,0,0,26.0000,0,1,0,0,1
336,1228,2,32.00,0,0,13.0000,0,1,0,0,1
337,1229,3,39.00,0,2,7.2292,0,1,1,0,0
338,1230,2,25.00,0,0,31.5000,0,1,0,0,1
339,1231,3,0.00,0,0,7.2292,0,1,1,0,0
340,1232,2,18.00,0,0,10.5000,0,1,0,0,1
341,1233,3,32.00,0,0,7.5792,0,1,0,0,1
342,1234,3,0.00,1,9,69.5500,0,1,0,0,1
343,1235,1,58.00,0,1,512.3292,1,0,1,0,0
344,1236,3,0.00,1,1,14.5000,0,1,0,0,1
345,1237,3,16.00,0,0,7.6500,1,0,0,0,1
346,1238,2,26.00,0,0,13.0000,0,1,0,0,1
347,1239,3,38.00,0,0,7.2292,1,0,1,0,0
348,1240,2,24.00,0,0,13.5000,0,1,0,0,1
349,1241,2,31.00,0,0,21.0000,1,0,0,0,1
350,1242,1,45.00,0,1,63.3583,1,0,1,0,0
351,1243,2,25.00,0,0,10.5000,0,1,0,0,1
352,1244,2,18.00,0,0,73.5000,0,1,0,0,1
353,1245,2,49.00,1,2,65.0000,0,1,0,0,1
354,1246,3,0.17,1,2,20.5750,1,0,0,0,1
355,1247,1,50.00,0,0,26.0000,0,1,0,0,1
356,1248,1,59.00,2,0,51.4792,1,0,0,0,1
357,1249,3,0.00,0,0,7.8792,0,1,0,0,1
358,1250,3,0.00,0,0,7.7500,0,1,0,1,0
359,1251,3,30.00,1,0,15.5500,1,0,0,0,1
360,1252,3,14.50,8,2,69.5500,0,1,0,0,1
361,1253,2,24.00,1,1,37.0042,1,0,1,0,0
362,1254,2,31.00,0,0,21.0000,1,0,0,0,1
363,1255,3,27.00,0,0,8.6625,0,1,0,0,1
364,1256,1,25.00,1,0,55.4417,1,0,1,0,0
365,1257,3,0.00,1,9,69.5500,1,0,0,0,1
366,1258,3,0.00,1,0,14.4583,0,1,1,0,0
367,1259,3,22.00,0,0,39.6875,1,0,0,0,1
368,1260,1,45.00,0,1,59.4000,1,0,1,0,0
369,1261,2,29.00,0,0,13.8583,0,1,1,0,0
370,1262,2,21.00,1,0,11.5000,0,1,0,0,1
371,1263,1,31.00,0,0,134.5000,1,0,1,0,0
372,1264,1,49.00,0,0,0.0000,0,1,0,0,1
373,1265,2,44.00,0,0,13.0000,0,1,0,0,1
374,1266,1,54.00,1,1,81.8583,1,0,0,0,1
375,1267,1,45.00,0,0,262.3750,1,0,1,0,0
376,1268,3,22.00,2,0,8.6625,1,0,0,0,1
377,1269,2,21.00,0,0,11.5000,0,1,0,0,1
378,1270,1,55.00,0,0,50.0000,0,1,0,0,1
379,1271,3,5.00,4,2,31.3875,0,1,0,0,1
380,1272,3,0.00,0,0,7.7500,0,1,0,1,0
381,1273,3,26.00,0,0,7.8792,0,1,0,1,0
382,1274,3,0.00,0,0,14.5000,1,0,0,0,1
383,1275,3,19.00,1,0,16.1000,1,0,0,0,1
384,1276,2,0.00,0,0,12.8750,0,1,0,0,1
385,1277,2,24.00,1,2,65.0000,1,0,0,0,1
386,1278,3,24.00,0,0,7.7750,0,1,0,0,1
387,1279,2,57.00,0,0,13.0000,0,1,0,0,1
388,1280,3,21.00,0,0,7.7500,0,1,0,1,0
389,1281,3,6.00,3,1,21.0750,0,1,0,0,1
390,1282,1,23.00,0,0,93.5000,0,1,0,0,1
391,1283,1,51.00,0,1,39.4000,1,0,0,0,1
392,1284,3,13.00,0,2,20.2500,0,1,0,0,1
393,1285,2,47.00,0,0,10.5000,0,1,0,0,1
394,1286,3,29.00,3,1,22.0250,0,1,0,0,1
395,1287,1,18.00,1,0,60.0000,1,0,0,0,1
396,1288,3,24.00,0,0,7.2500,0,1,0,1,0
397,1289,1,48.00,1,1,79.2000,1,0,1,0,0
398,1290,3,22.00,0,0,7.7750,0,1,0,0,1
399,1291,3,31.00,0,0,7.7333,0,1,0,1,0
400,1292,1,30.00,0,0,164.8667,1,0,0,0,1
401,1293,2,38.00,1,0,21.0000,0,1,0,0,1
402,1294,1,22.00,0,1,59.4000,1,0,1,0,0
403,1295,1,17.00,0,0,47.1000,0,1,0,0,1
404,1296,1,43.00,1,0,27.7208,0,1,1,0,0
405,1297,2,20.00,0,0,13.8625,0,1,1,0,0
406,1298,2,23.00,1,0,10.5000,0,1,0,0,1
407,1299,1,50.00,1,1,211.5000,0,1,1,0,0
408,1300,3,0.00,0,0,7.7208,1,0,0,1,0
409,1301,3,3.00,1,1,13.7750,1,0,0,0,1
410,1302,3,0.00,0,0,7.7500,1,0,0,1,0
411,1303,1,37.00,1,0,90.0000,1,0,0,1,0
412,1304,3,28.00,0,0,7.7750,1,0,0,0,1
413,1305,3,0.00,0,0,8.0500,0,1,0,0,1
414,1306,1,39.00,0,0,108.9000,1,0,1,0,0
415,1307,3,38.50,0,0,7.2500,0,1,0,0,1
416,1308,3,0.00,0,0,8.0500,0,1,0,0,1
417,1309,3,0.00,1,1,22.3583,0,1,1,0,0

In [30]:
df.to_csv('clean_01.csv')

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
data = pd.read_csv('clear_data.csv')
train = pd.read_csv('train.csv')
X = data
y = train['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

In [5]:
rf2 = RandomForestClassifier(n_estimators=100,max_depth=5).fit(X_train, y_train)

In [6]:
rf2.predict(X_train)

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [35]:
rf2.predict(X)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [15]:
data = pd.read_csv('clean_01.csv')

X1 = data

In [16]:
X1.isnull().sum()

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           1
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [17]:
X1.loc[X1['Fare'].isnull(),'Fare']=0

In [18]:
X1.isnull().sum()

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [19]:
rf2.predict(X1)

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
      dtype=int64)

In [29]:
rf2.predict(X1).shape

(418,)

In [30]:
a = pd.Series(rf2.predict(X1))
a.columns=['Survived']
a

0      0
1      0
2      0
3      0
4      0
5      0
6      1
7      0
8      1
9      0
10     1
11     0
12     1
13     0
14     1
15     1
16     0
17     0
18     0
19     0
20     1
21     0
22     1
23     1
24     1
25     0
26     1
27     0
28     0
29     1
30     0
31     0
32     0
33     1
34     1
35     0
36     1
37     0
38     0
39     1
40     0
41     1
42     0
43     1
44     1
45     0
46     0
47     1
48     1
49     0
50     0
51     0
52     1
53     1
54     1
55     0
56     0
57     0
58     1
59     1
60     0
61     0
62     0
63     1
64     1
65     1
66     1
67     0
68     0
69     1
70     1
71     0
72     0
73     0
74     1
75     1
76     1
77     1
78     0
79     1
80     1
81     0
82     0
83     1
84     1
85     1
86     1
87     0
88     1
89     1
90     0
91     1
92     1
93     1
94     0
95     0
96     1
97     0
98     0
99     0
100    1
101    0
102    1
103    0
104    0
105    0
106    0
107    1
108    1
109    0
110    0
111    1
112    1
113    1
114    1
115    0
116    1
117    1
118    1
119    1
120    1
121    1
122    1
123    0
124    1
125    0
126    0
127    1
128    0
129    0
130    0
131    0
132    0
133    1
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    1
142    1
143    0
144    0
145    0
146    1
147    0
148    1
149    0
150    1
151    1
152    0
153    0
154    0
155    0
156    1
157    0
158    0
159    0
160    1
161    1
162    1
163    1
164    0
165    0
166    0
167    0
168    1
169    0
170    1
171    0
172    0
173    1
174    0
175    1
176    1
177    1
178    1
179    1
180    0
181    1
182    1
183    1
184    1
185    0
186    1
187    0
188    0
189    0
190    0
191    1
192    0
193    0
194    0
195    0
196    1
197    0
198    0
199    1
200    1
201    1
202    1
203    1
204    0
205    1
206    0
207    0
208    1
209    0
210    0
211    1
212    0
213    1
214    0
215    0
216    1
217    0
218    1
219    1
220    1
221    0
222    1
223    0
224    1
225    1
226    0
227    1
228    0
229    0
230    0
231    1
232    0
233    1
234    1
235    0
236    1
237    0
238    1
239    1
240    1
241    1
242    1
243    1
244    1
245    0
246    1
247    0
248    1
249    1
250    1
251    0
252    1
253    0
254    0
255    1
256    1
257    0
258    1
259    0
260    0
261    0
262    1
263    1
264    0
265    1
266    1
267    1
268    1
269    0
270    1
271    1
272    1
273    1
274    1
275    1
276    0
277    0
278    0
279    0
280    0
281    1
282    1
283    0
284    1
285    0
286    1
287    0
288    1
289    1
290    1
291    1
292    1
293    0
294    0
295    0
296    1
297    1
298    0
299    0
300    0
301    1
302    0
303    0
304    1
305    1
306    1
307    1
308    0
309    0
310    0
311    0
312    1
313    0
314    1
315    1
316    1
317    0
318    0
319    0
320    0
321    0
322    0
323    0
324    1
325    0
326    1
327    0
328    0
329    0
330    1
331    0
332    1
333    1
334    0
335    0
336    0
337    0
338    0
339    1
340    0
341    0
342    1
343    1
344    1
345    0
346    0
347    0
348    0
349    1
350    1
351    0
352    0
353    0
354    1
355    0
356    1
357    1
358    1
359    0
360    0
361    1
362    1
363    0
364    1
365    0
366    1
367    0
368    1
369    0
370    0
371    1
372    0
373    0
374    1
375    1
376    0
377    0
378    0
379    0
380    1
381    0
382    1
383    0
384    1
385    1
386    0
387    0
388    0
389    0
390    0
391    1
392    0
393    0
394    0
395    1
396    0
397    1
398    0
399    0
400    1
401    0
402    1
403    0
404    1
405    0
406    0
407    1
408    1
409    1
410    1
411    1
412    0
413    1
414    1
415    0
416    1
417    1
dtype: int64

In [31]:
data=X1.loc[:,['PassengerId']]
data

     PassengerId
0            892
1            893
2            894
3            895
4            896
5            897
6            898
7            899
8            900
9            901
10           902
11           903
12           904
13           905
14           906
15           907
16           908
17           909
18           910
19           911
20           912
21           913
22           914
23           915
24           916
25           917
26           918
27           919
28           920
29           921
30           922
31           923
32           924
33           925
34           926
35           927
36           928
37           929
38           930
39           931
40           932
41           933
42           934
43           935
44           936
45           937
46           938
47           939
48           940
49           941
50           942
51           943
52           944
53           945
54           946
55           947
56           948
57           949
58           950
59           951
60           952
61           953
62           954
63           955
64           956
65           957
66           958
67           959
68           960
69           961
70           962
71           963
72           964
73           965
74           966
75           967
76           968
77           969
78           970
79           971
80           972
81           973
82           974
83           975
84           976
85           977
86           978
87           979
88           980
89           981
90           982
91           983
92           984
93           985
94           986
95           987
96           988
97           989
98           990
99           991
100          992
101          993
102          994
103          995
104          996
105          997
106          998
107          999
108         1000
109         1001
110         1002
111         1003
112         1004
113         1005
114         1006
115         1007
116         1008
117         1009
118         1010
119         1011
120         1012
121         1013
122         1014
123         1015
124         1016
125         1017
126         1018
127         1019
128         1020
129         1021
130         1022
131         1023
132         1024
133         1025
134         1026
135         1027
136         1028
137         1029
138         1030
139         1031
140         1032
141         1033
142         1034
143         1035
144         1036
145         1037
146         1038
147         1039
148         1040
149         1041
150         1042
151         1043
152         1044
153         1045
154         1046
155         1047
156         1048
157         1049
158         1050
159         1051
160         1052
161         1053
162         1054
163         1055
164         1056
165         1057
166         1058
167         1059
168         1060
169         1061
170         1062
171         1063
172         1064
173         1065
174         1066
175         1067
176         1068
177         1069
178         1070
179         1071
180         1072
181         1073
182         1074
183         1075
184         1076
185         1077
186         1078
187         1079
188         1080
189         1081
190         1082
191         1083
192         1084
193         1085
194         1086
195         1087
196         1088
197         1089
198         1090
199         1091
200         1092
201         1093
202         1094
203         1095
204         1096
205         1097
206         1098
207         1099
208         1100
209         1101
210         1102
211         1103
212         1104
213         1105
214         1106
215         1107
216         1108
217         1109
218         1110
219         1111
220         1112
221         1113
222         1114
223         1115
224         1116
225         1117
226         1118
227         1119
228         1120
229         1121
230         1122
231         1123
232         1124
233         1125
234         1126
235         1127
236         1128
237         1129
238         1130
239         1131
240         1132
241         1133
242         1134
243         1135
244         1136
245         1137
246         1138
247         1139
248         1140
249         1141
250         1142
251         1143
252         1144
253         1145
254         1146
255         1147
256         1148
257         1149
258         1150
259         1151
260         1152
261         1153
262         1154
263         1155
264         1156
265         1157
266         1158
267         1159
268         1160
269         1161
270         1162
271         1163
272         1164
273         1165
274         1166
275         1167
276         1168
277         1169
278         1170
279         1171
280         1172
281         1173
282         1174
283         1175
284         1176
285         1177
286         1178
287         1179
288         1180
289         1181
290         1182
291         1183
292         1184
293         1185
294         1186
295         1187
296         1188
297         1189
298         1190
299         1191
300         1192
301         1193
302         1194
303         1195
304         1196
305         1197
306         1198
307         1199
308         1200
309         1201
310         1202
311         1203
312         1204
313         1205
314         1206
315         1207
316         1208
317         1209
318         1210
319         1211
320         1212
321         1213
322         1214
323         1215
324         1216
325         1217
326         1218
327         1219
328         1220
329         1221
330         1222
331         1223
332         1224
333         1225
334         1226
335         1227
336         1228
337         1229
338         1230
339         1231
340         1232
341         1233
342         1234
343         1235
344         1236
345         1237
346         1238
347         1239
348         1240
349         1241
350         1242
351         1243
352         1244
353         1245
354         1246
355         1247
356         1248
357         1249
358         1250
359         1251
360         1252
361         1253
362         1254
363         1255
364         1256
365         1257
366         1258
367         1259
368         1260
369         1261
370         1262
371         1263
372         1264
373         1265
374         1266
375         1267
376         1268
377         1269
378         1270
379         1271
380         1272
381         1273
382         1274
383         1275
384         1276
385         1277
386         1278
387         1279
388         1280
389         1281
390         1282
391         1283
392         1284
393         1285
394         1286
395         1287
396         1288
397         1289
398         1290
399         1291
400         1292
401         1293
402         1294
403         1295
404         1296
405         1297
406         1298
407         1299
408         1300
409         1301
410         1302
411         1303
412         1304
413         1305
414         1306
415         1307
416         1308
417         1309

In [32]:
result= pd.concat([data,a],axis=1)

In [33]:
result

     PassengerId  0
0            892  0
1            893  0
2            894  0
3            895  0
4            896  0
5            897  0
6            898  1
7            899  0
8            900  1
9            901  0
10           902  1
11           903  0
12           904  1
13           905  0
14           906  1
15           907  1
16           908  0
17           909  0
18           910  0
19           911  0
20           912  1
21           913  0
22           914  1
23           915  1
24           916  1
25           917  0
26           918  1
27           919  0
28           920  0
29           921  1
30           922  0
31           923  0
32           924  0
33           925  1
34           926  1
35           927  0
36           928  1
37           929  0
38           930  0
39           931  1
40           932  0
41           933  1
42           934  0
43           935  1
44           936  1
45           937  0
46           938  0
47           939  1
48           940  1
49           941  0
50           942  0
51           943  0
52           944  1
53           945  1
54           946  1
55           947  0
56           948  0
57           949  0
58           950  1
59           951  1
60           952  0
61           953  0
62           954  0
63           955  1
64           956  1
65           957  1
66           958  1
67           959  0
68           960  0
69           961  1
70           962  1
71           963  0
72           964  0
73           965  0
74           966  1
75           967  1
76           968  1
77           969  1
78           970  0
79           971  1
80           972  1
81           973  0
82           974  0
83           975  1
84           976  1
85           977  1
86           978  1
87           979  0
88           980  1
89           981  1
90           982  0
91           983  1
92           984  1
93           985  1
94           986  0
95           987  0
96           988  1
97           989  0
98           990  0
99           991  0
100          992  1
101          993  0
102          994  1
103          995  0
104          996  0
105          997  0
106          998  0
107          999  1
108         1000  1
109         1001  0
110         1002  0
111         1003  1
112         1004  1
113         1005  1
114         1006  1
115         1007  0
116         1008  1
117         1009  1
118         1010  1
119         1011  1
120         1012  1
121         1013  1
122         1014  1
123         1015  0
124         1016  1
125         1017  0
126         1018  0
127         1019  1
128         1020  0
129         1021  0
130         1022  0
131         1023  0
132         1024  0
133         1025  1
134         1026  0
135         1027  0
136         1028  0
137         1029  0
138         1030  0
139         1031  0
140         1032  0
141         1033  1
142         1034  1
143         1035  0
144         1036  0
145         1037  0
146         1038  1
147         1039  0
148         1040  1
149         1041  0
150         1042  1
151         1043  1
152         1044  0
153         1045  0
154         1046  0
155         1047  0
156         1048  1
157         1049  0
158         1050  0
159         1051  0
160         1052  1
161         1053  1
162         1054  1
163         1055  1
164         1056  0
165         1057  0
166         1058  0
167         1059  0
168         1060  1
169         1061  0
170         1062  1
171         1063  0
172         1064  0
173         1065  1
174         1066  0
175         1067  1
176         1068  1
177         1069  1
178         1070  1
179         1071  1
180         1072  0
181         1073  1
182         1074  1
183         1075  1
184         1076  1
185         1077  0
186         1078  1
187         1079  0
188         1080  0
189         1081  0
190         1082  0
191         1083  1
192         1084  0
193         1085  0
194         1086  0
195         1087  0
196         1088  1
197         1089  0
198         1090  0
199         1091  1
200         1092  1
201         1093  1
202         1094  1
203         1095  1
204         1096  0
205         1097  1
206         1098  0
207         1099  0
208         1100  1
209         1101  0
210         1102  0
211         1103  1
212         1104  0
213         1105  1
214         1106  0
215         1107  0
216         1108  1
217         1109  0
218         1110  1
219         1111  1
220         1112  1
221         1113  0
222         1114  1
223         1115  0
224         1116  1
225         1117  1
226         1118  0
227         1119  1
228         1120  0
229         1121  0
230         1122  0
231         1123  1
232         1124  0
233         1125  1
234         1126  1
235         1127  0
236         1128  1
237         1129  0
238         1130  1
239         1131  1
240         1132  1
241         1133  1
242         1134  1
243         1135  1
244         1136  1
245         1137  0
246         1138  1
247         1139  0
248         1140  1
249         1141  1
250         1142  1
251         1143  0
252         1144  1
253         1145  0
254         1146  0
255         1147  1
256         1148  1
257         1149  0
258         1150  1
259         1151  0
260         1152  0
261         1153  0
262         1154  1
263         1155  1
264         1156  0
265         1157  1
266         1158  1
267         1159  1
268         1160  1
269         1161  0
270         1162  1
271         1163  1
272         1164  1
273         1165  1
274         1166  1
275         1167  1
276         1168  0
277         1169  0
278         1170  0
279         1171  0
280         1172  0
281         1173  1
282         1174  1
283         1175  0
284         1176  1
285         1177  0
286         1178  1
287         1179  0
288         1180  1
289         1181  1
290         1182  1
291         1183  1
292         1184  1
293         1185  0
294         1186  0
295         1187  0
296         1188  1
297         1189  1
298         1190  0
299         1191  0
300         1192  0
301         1193  1
302         1194  0
303         1195  0
304         1196  1
305         1197  1
306         1198  1
307         1199  1
308         1200  0
309         1201  0
310         1202  0
311         1203  0
312         1204  1
313         1205  0
314         1206  1
315         1207  1
316         1208  1
317         1209  0
318         1210  0
319         1211  0
320         1212  0
321         1213  0
322         1214  0
323         1215  0
324         1216  1
325         1217  0
326         1218  1
327         1219  0
328         1220  0
329         1221  0
330         1222  1
331         1223  0
332         1224  1
333         1225  1
334         1226  0
335         1227  0
336         1228  0
337         1229  0
338         1230  0
339         1231  1
340         1232  0
341         1233  0
342         1234  1
343         1235  1
344         1236  1
345         1237  0
346         1238  0
347         1239  0
348         1240  0
349         1241  1
350         1242  1
351         1243  0
352         1244  0
353         1245  0
354         1246  1
355         1247  0
356         1248  1
357         1249  1
358         1250  1
359         1251  0
360         1252  0
361         1253  1
362         1254  1
363         1255  0
364         1256  1
365         1257  0
366         1258  1
367         1259  0
368         1260  1
369         1261  0
370         1262  0
371         1263  1
372         1264  0
373         1265  0
374         1266  1
375         1267  1
376         1268  0
377         1269  0
378         1270  0
379         1271  0
380         1272  1
381         1273  0
382         1274  1
383         1275  0
384         1276  1
385         1277  1
386         1278  0
387         1279  0
388         1280  0
389         1281  0
390         1282  0
391         1283  1
392         1284  0
393         1285  0
394         1286  0
395         1287  1
396         1288  0
397         1289  1
398         1290  0
399         1291  0
400         1292  1
401         1293  0
402         1294  1
403         1295  0
404         1296  1
405         1297  0
406         1298  0
407         1299  1
408         1300  1
409         1301  1
410         1302  1
411         1303  1
412         1304  0
413         1305  1
414         1306  1
415         1307  0
416         1308  1
417         1309  1

In [35]:
result.columns=['PassengerId','Survived']
result

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         1
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         0
19           911         0
20           912         1
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         1
30           922         0
31           923         0
32           924         0
33           925         1
34           926         1
35           927         0
36           928         1
37           929         0
38           930         0
39           931         1
40           932         0
41           933         1
42           934         0
43           935         1
44           936         1
45           937         0
46           938         0
47           939         1
48           940         1
49           941         0
50           942         0
51           943         0
52           944         1
53           945         1
54           946         1
55           947         0
56           948         0
57           949         0
58           950         1
59           951         1
60           952         0
61           953         0
62           954         0
63           955         1
64           956         1
65           957         1
66           958         1
67           959         0
68           960         0
69           961         1
70           962         1
71           963         0
72           964         0
73           965         0
74           966         1
75           967         1
76           968         1
77           969         1
78           970         0
79           971         1
80           972         1
81           973         0
82           974         0
83           975         1
84           976         1
85           977         1
86           978         1
87           979         0
88           980         1
89           981         1
90           982         0
91           983         1
92           984         1
93           985         1
94           986         0
95           987         0
96           988         1
97           989         0
98           990         0
99           991         0
100          992         1
101          993         0
102          994         1
103          995         0
104          996         0
105          997         0
106          998         0
107          999         1
108         1000         1
109         1001         0
110         1002         0
111         1003         1
112         1004         1
113         1005         1
114         1006         1
115         1007         0
116         1008         1
117         1009         1
118         1010         1
119         1011         1
120         1012         1
121         1013         1
122         1014         1
123         1015         0
124         1016         1
125         1017         0
126         1018         0
127         1019         1
128         1020         0
129         1021         0
130         1022         0
131         1023         0
132         1024         0
133         1025         1
134         1026         0
135         1027         0
136         1028         0
137         1029         0
138         1030         0
139         1031         0
140         1032         0
141         1033         1
142         1034         1
143         1035         0
144         1036         0
145         1037         0
146         1038         1
147         1039         0
148         1040         1
149         1041         0
150         1042         1
151         1043         1
152         1044         0
153         1045         0
154         1046         0
155         1047         0
156         1048         1
157         1049         0
158         1050         0
159         1051         0
160         1052         1
161         1053         1
162         1054         1
163         1055         1
164         1056         0
165         1057         0
166         1058         0
167         1059         0
168         1060         1
169         1061         0
170         1062         1
171         1063         0
172         1064         0
173         1065         1
174         1066         0
175         1067         1
176         1068         1
177         1069         1
178         1070         1
179         1071         1
180         1072         0
181         1073         1
182         1074         1
183         1075         1
184         1076         1
185         1077         0
186         1078         1
187         1079         0
188         1080         0
189         1081         0
190         1082         0
191         1083         1
192         1084         0
193         1085         0
194         1086         0
195         1087         0
196         1088         1
197         1089         0
198         1090         0
199         1091         1
200         1092         1
201         1093         1
202         1094         1
203         1095         1
204         1096         0
205         1097         1
206         1098         0
207         1099         0
208         1100         1
209         1101         0
210         1102         0
211         1103         1
212         1104         0
213         1105         1
214         1106         0
215         1107         0
216         1108         1
217         1109         0
218         1110         1
219         1111         1
220         1112         1
221         1113         0
222         1114         1
223         1115         0
224         1116         1
225         1117         1
226         1118         0
227         1119         1
228         1120         0
229         1121         0
230         1122         0
231         1123         1
232         1124         0
233         1125         1
234         1126         1
235         1127         0
236         1128         1
237         1129         0
238         1130         1
239         1131         1
240         1132         1
241         1133         1
242         1134         1
243         1135         1
244         1136         1
245         1137         0
246         1138         1
247         1139         0
248         1140         1
249         1141         1
250         1142         1
251         1143         0
252         1144         1
253         1145         0
254         1146         0
255         1147         1
256         1148         1
257         1149         0
258         1150         1
259         1151         0
260         1152         0
261         1153         0
262         1154         1
263         1155         1
264         1156         0
265         1157         1
266         1158         1
267         1159         1
268         1160         1
269         1161         0
270         1162         1
271         1163         1
272         1164         1
273         1165         1
274         1166         1
275         1167         1
276         1168         0
277         1169         0
278         1170         0
279         1171         0
280         1172         0
281         1173         1
282         1174         1
283         1175         0
284         1176         1
285         1177         0
286         1178         1
287         1179         0
288         1180         1
289         1181         1
290         1182         1
291         1183         1
292         1184         1
293         1185         0
294         1186         0
295         1187         0
296         1188         1
297         1189         1
298         1190         0
299         1191         0
300         1192         0
301         1193         1
302         1194         0
303         1195         0
304         1196         1
305         1197         1
306         1198         1
307         1199         1
308         1200         0
309         1201         0
310         1202         0
311         1203         0
312         1204         1
313         1205         0
314         1206         1
315         1207         1
316         1208         1
317         1209         0
318         1210         0
319         1211         0
320         1212         0
321         1213         0
322         1214         0
323         1215         0
324         1216         1
325         1217         0
326         1218         1
327         1219         0
328         1220         0
329         1221         0
330         1222         1
331         1223         0
332         1224         1
333         1225         1
334         1226         0
335         1227         0
336         1228         0
337         1229         0
338         1230         0
339         1231         1
340         1232         0
341         1233         0
342         1234         1
343         1235         1
344         1236         1
345         1237         0
346         1238         0
347         1239         0
348         1240         0
349         1241         1
350         1242         1
351         1243         0
352         1244         0
353         1245         0
354         1246         1
355         1247         0
356         1248         1
357         1249         1
358         1250         1
359         1251         0
360         1252         0
361         1253         1
362         1254         1
363         1255         0
364         1256         1
365         1257         0
366         1258         1
367         1259         0
368         1260         1
369         1261         0
370         1262         0
371         1263         1
372         1264         0
373         1265         0
374         1266         1
375         1267         1
376         1268         0
377         1269         0
378         1270         0
379         1271         0
380         1272         1
381         1273         0
382         1274         1
383         1275         0
384         1276         1
385         1277         1
386         1278         0
387         1279         0
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         1
405         1297         0
406         1298         0
407         1299         1
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         0
413         1305         1
414         1306         1
415         1307         0
416         1308         1
417         1309         1

In [37]:
result.to_csv('titanic_result007.csv')